#!/bin/bash

# Copyright (C) 2012 Michael K Johnson
# 
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
# AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
# IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# This is intended to be a very minimal shell script that implements
# fetching GPS almanac data from Sony for Sony cameras with GPS, and
# writing that data to an SD card that is currently mounted.  It is
# trivial.  Please modify it.  It has been tested on exactly one Linux
# system and one Sony camera.
#
# The URLs and filename I learned from looking at the source code to
# gpsassist-update http://code.google.com/p/gpsassist-update/ but I
# obviously copied no code.

die ()
{
    echo $*
    exit 1
}

cd $HOME || die no home "$HOME"
[ -d .sonygpsassist ] || mkdir .sonygpsassist || die could not make .sonygpsassist directory

cd .sonygpsassist

curl http://control.d-imaging.sony.co.jp/GPS/assistme.md5 > assistme.md5 || die failed to get md5 file
if [ -f assistme.dat ] && echo "$(cat assistme.md5)assistme.dat" | md5sum -c - ; then
    echo using already-cached data
else
    # must need a new copy
    curl http://control.d-imaging.sony.co.jp/GPS/assistme.dat > assistme.dat || die failed to get data file
    echo "$(cat assistme.md5)assistme.dat" | md5sum -c - || die md5 check failed
fi

for dir in $(cat /proc/mounts | awk '{print $2}' | grep media) ; do
    if [ -d "${dir}/PRIVATE/SONY" ] ; then
        if [ ! -d "${dir}/PRIVATE/SONY/GPS" ] ; then
            mkdir "${dir}/PRIVATE/SONY/GPS" || die failed to create GPS dir
            echo created GPS data directory
        fi
        if cp assistme.dat "${dir}/PRIVATE/SONY/GPS/" ; then
            echo copied assistme.dat to "${dir}/PRIVATE/SONY/GPS/"
        else
            die failed to copy assistme.dat to "${dir}/PRIVATE/SONY/GPS/"
        fi
    fi
done

exit 0
